name: deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
          python-version: '3.13'

      - name: Install dependencies
        run: |
          uv sync --without dev

      - name: Build package
        run: |
          uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
