name: release

on:
  push:
    tags:
      # Push events to matching 'v*', i.e. 'v1.0', 'v20.15.10b5'
      - 'v*'

jobs:
  release:
    name: Create Release & Deploy on TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 'latest'
          python-version: '3.13'

      - name: Install dependencies
        run: |
          uv sync

      - name: Build package
        run: |
          uv build
          echo "WHEEL=$(ls dist/*.whl)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.WHEEL }}
          asset_name: $(basename ${{ env.WHEEL }})
          asset_content_type: application/zip

      - name: Publish Package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
